### ISSUE TITLE
triple quote won't accept sticks or hashes

### ISSUE THREAD

**Issue by shriram** [greghendershott/markdown#84]
I'm trying to incorporate Markdown into a Scribble document, like so:
```
#lang scribble/base

@(require markdown markdown/scrib scribble/decode)

@(define (include-markdown-file filename)
   (decode
     (xexprs->scribble-pres
       (with-input-from-file filename read-markdown))))

<scribbly stuff>

@(include-markdown-file "try.md")
```

But the following, which Github's renderer is perfectly happy with, does not seem to work here. Note that the text below (the content of `"try.md"`) is *within* a three-backquote pair (which I can't show here due to quotation, but see image):
```
A ::= B
    | C
    | D # which is an E
```
![image](https://user-images.githubusercontent.com/75030/92529652-e1298700-f1f8-11ea-8f45-29e513223526.png)

Both the stick and the hash cause the parser to error.

Is this somehow not legal Markdown? It seems awfully useful to be able to write these things inside verbatim blocks, because they quite often occur in code, which is a major use of triple-backtick.

More curiously, these are all accepted in SINGLE-backticks: see this file, where there is a single-backtick (not shown, but see image below) before and after this block:
```
A ::= B
    | C
    | D # which is an E
```

![image](https://user-images.githubusercontent.com/75030/92529799-2b126d00-f1f9-11ea-89af-dffd924866a0.png)

**Comment by LiberalArtist** [comment]
I know this bug!

The problem is with `xexprs->scribble-pres`, not `read-markdown`, as illustrated by the following program:
```racket
#lang at-exp racket

(require markdown markdown/scrib scribble/decode)

(define xs
  (parameterize  ([current-input-port
                   (open-input-string
                    @string-append{```
                    A ::= B
                    | C
                    | D # which is an E
                    ```})])
    (read-markdown)))

xs

(with-handlers ([exn:fail? (λ (e) e)])
  (xexprs->scribble-pres xs))
```

The issue is that `xs` is `'((pre () (code () "A ::= B\n| C\n| D # which is an E")))`, which `xexprs->scribble-pres` tries to process here: https://github.com/greghendershott/markdown/blob/4c79d5654392c112b0f35c8847d7a8991a56a0d0/markdown/scrib.rkt#L47-L48

… but [`codeblock`](https://docs.racket-lang.org/scribble/scribble_manual_code.html#(form._((lib._scribble%2Fmanual..rkt)._codeblock))) expects to use a `#lang`-specified reader to parse (and maybe colorize?) the given text.

I ran into this issue when trying to use a fenced codeblock with a non-racket language, which showed up as `[class "brush: python"]` and caused the `match` to fail. I forked `markdown/scrib` at https://github.com/DigitalRicoeur/pydrnlp/blob/70dcf323916f659ad82854f5373aa1052f3acf74/scribblings/markdown.rkt to add an optional second argument to `xexprs->scribble-pres` to override the default handling (or non-handling) of an x-expression, which I use [here](https://github.com/DigitalRicoeur/pydrnlp/blob/70dcf323916f659ad82854f5373aa1052f3acf74/scribblings/python-doc-lang.rkt#L408-L422).

But I guess I never got around to reporting the bug …

**Comment by greghendershott** [comment]
For context: When I added this function, what seems like a decade ago, I think it was in response to samth making a casual comment "it would be neat if...".

In hindsight, maybe I should have offered it in the form of example code -- as opposed to any implied promise it would be `markdown->scribble/dwim` for everyone's "what I mean". :smile:

Maybe I could still "tilt" it that way, by adding such a caveat to its documentation.

Anyway, in that light, the treatment of `codeblock` -- as well as the handling of `<blockquote> => (centered)` you mention in #85 -- would be seen for what they are: Judgments of what would be "reasonable" that are old and not very carefully considered.

---

Having said all that: You could call your own function before maybe delegating to mine. I also like @LiberalArtist 's variation where you supply your optional function that mine calls before maybe proceeding. Although I'm not sure the latter adds _that_ much over the former, in substance, it definitely would be a sort of "documentable opportunity" -- a great place for the docs to be appropriately self-deprecating like what I wrote above?

And, probably I should change:

```racket
  [`(pre () (code () ,s)) (codeblock s)] 
```

to something like a `verbatim` nested in a paragraph?  So at least the default behavior isn't plain wrong?

**Comment by greghendershott** [comment]
> Although I'm not sure the latter adds that much over the former, in substance,

After more coffee: Oh right. My status quo function does too much. It gratuitously composes mapping over a list, with transforming each item.

I think what I might do is split out a singular `markdown->scribble` function and provide that. Re-implement the status quo function using that, and adding the optional argument. Add caveats to docs.

**Comment by greghendershott** [comment]
I closed this with a commit.

#85 is still open with a question for you @shriram.

**Comment by greghendershott** [comment]
p.s. Thank you @LiberalArtist for the idea of an optional additional argument to override the conversion chosen!
